FROM jenkins/jenkins:lts-jdk17

USER root

# Install Python, pip, docker-compose
RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-pip \
    docker-compose \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Allow Jenkins to run Docker
RUN groupadd -f docker && usermod -aG docker jenkins

USER jenkins
